### ISSUE TITLE
Structure of `isA` in `TypeConstraint`

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-json-export#17]
Currently, the `isA` property of a `TypeConstraint` has `_name` and `_namespace` properties, as shown below:
```json
{
    "min": 0,
    "max": 1,
    "constraints": [
    {
        "type": "TypeConstraint",
        "isA": {
            "_namespace": "shr.lab",
            "_name": "TestMethod"
        },
        "onValue": false,
        "path": ""
    }
    ],
    "type": "IdentifiableValue",
    "label": "shr.observation:Method",
    "identifier": {
        "label": "Method",
        "type": "Identifier",
        "namespace": "shr.observation"
    }
}
```

These are intended to be private properties (hence the `_` prefix).  Since `isA` is an `Identifier` in the models, I think this should be represented in the JSON the same way identifiers are represented elsewhere.  So, the example above probably should be:

```json
{
    "min": 0,
    "max": 1,
    "constraints": [
    {
        "type": "TypeConstraint",
        "isA": {
            "type": "Identifier",
            "label": "TestMethod",
            "namespace": "shr.lab"
        },
        "onValue": false,
        "path": ""
    }
    ],
    "type": "IdentifiableValue",
    "label": "shr.observation:Method",
    "identifier": {
        "label": "Method",
        "type": "Identifier",
        "namespace": "shr.observation"
    }
}
```

@gregquinn2001, @Dtphelan1 : Any objections?

**Comment by Dtphelan1** [comment]
This makes sense to me!  I'm on board the with suggested change.

**Comment by gregquinn2001** [comment]
sounds good to me too. Should be simple to update SSVE as well.

**Comment by Abhijay** [comment]
I'll go ahead and update the SSVE then.

**Comment by Abhijay** [comment]
Latest PR adds support for the isA value change:
https://github.com/standardhealth/spec_json2html/pull/9

**Comment by cmoesel** [comment]
This is still an open issue in spec_json2html, but for the purposes of this project (shr-json-export), it is fixed.
